learning_users/basic_app/urls.py
from django.urls import path, include
from basic_app import views

# template URLS
app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name="register"),
    path("login/", views.user_login,name='user_login'),
]

learning_users/learning_users/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("basic/", include("basic_app.urls")),
    path("logout/", views.user_logout, name='logout'),
    path("special/", views.special, name='special'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional attributes

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    verify_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'verify_password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm, UserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo
from django.shortcuts import get_object_or_404


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')


@login_required
def special(request):
    return HttpResponse("You Are logged in successfully, Thats Good!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        print(user.username)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print("Invalid Credentials entered!")
            return HttpResponse('Invalid Login details Supplied!')
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                  </li>
                  {% if user.is_authenticated %}
                    <div class="text-center">
                        <img src="{{user.userprofileinfo.profile_pic.url}}" class="rounded" alt="">
                    </div>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                  </li>
                  {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
         {% block content %}
         <!-- Anything outside of this will be inherited if you extend -->
         {% endblock %}
    </div>
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block title %} Home Page {% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block title %} Registartion {% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1>Please login@#</h1>
        <form action="{% url 'basic_app:user_login' %}" method="post">
            {% csrf_token %}
                <label for="username">Username: </label>
                <input type="text" name="username" placeholder="Enter your username">

                <label for="password">Password: </label>
                <input type="password" name="password" placeholder="Enter your password">
                <input type="submit" value="Login" >
            
        </form>
    </div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block title %} Registration {% endblock %}
{% block content %}
    <div class="jumbotron">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}

                <input type="submit" name="" value="Register">
            </form>
        {% endif %}

    </div>
{% endblock %}